# Generated by Django 5.2.7 on 2025-12-10 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('current_active_cases', models.IntegerField(default=0)),
                ('max_concurrent_cases', models.IntegerField(default=5)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('clinician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('NEW_USER', 'New User'), ('COLLECTING_PROFILE', 'Collecting Profile'), ('COLLECTING_SYMPTOMS', 'Collecting Symptoms'), ('AI_FOLLOWUP_QUESTIONS', 'AI Follow-up Questions'), ('SUMMARY_AND_RECOMMENDATIONS', 'Summary and Recommendations'), ('AWAITING_CLINICIAN_DECISION', 'Awaiting Clinician Decision'), ('CONNECT_TO_CLINICIAN', 'Connect to Clinician'), ('CLINICIAN_CHAT_ACTIVE', 'Clinician Chat Active'), ('COMPLETED', 'Completed')], default='NEW_USER', max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('session_data', models.JSONField(default=dict)),
                ('ai_overview', models.TextField(blank=True, null=True)),
                ('recommendation_plan', models.TextField(blank=True, null=True)),
                ('escalated_to_clinician', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_from_user', models.BooleanField(default=True)),
                ('is_from_clinician', models.BooleanField(default=False)),
                ('message_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.patientsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('reason', models.TextField()),
                ('ai_assessment', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_queue', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation', to='whatsapp.patientsession')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientsession',
            index=models.Index(fields=['phone_number', 'state'], name='whatsapp_pa_phone_n_55a062_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsession',
            index=models.Index(fields=['escalated_to_clinician', 'assigned_clinician'], name='whatsapp_pa_escalat_41bf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['session', 'created_at'], name='whatsapp_me_session_530136_idx'),
        ),
    ]
